use crate::error::PremiumBondsError;
use anchor_lang::prelude::*;
use std::convert::TryInto;

/// Calculate a percentage fee from an amount based on basis points (1 basis point = 0.01%).
/// 10,000 basis points equals 100%.
///
/// # Parameters
/// * `amount` - The total amount in base units to apply the fee to.
/// * `fee_basis_points` - Fee rate in basis points.
///
/// # Returns
/// * `u64` - The calculated fee.
pub fn calculate_percentage_fee(amount: u64, fee_basis_points: u16) -> u64 {
    (amount as u128)
        .checked_mul(fee_basis_points as u128)
        .unwrap()
        .checked_div(10000)
        .unwrap()
        .try_into()
        .unwrap()
}

/// Derive a deterministic random ticket index from a seed and contextual inputs.
/// Uses SHA-256 hashing to produce uniform entropy scoped per tier, winner slot, and cycle.
///
/// # Parameters
/// * `seed` - Randomness seed generated by Switchboard.
/// * `tier_idx` - Prize tier index.
/// * `winner_slot` - Winner slot number inside the tier.
/// * `cycle_id` - Cycle ID of the drawing.
/// * `ticket_count` - Total tickets locked in this drawing.
///
/// # Returns
/// * `u64` - Deterministic winner ticket index modulo `ticket_count`.
pub fn derive_random_index(
    seed: &[u8; 32],
    tier_idx: u32,
    winner_slot: u32,
    cycle_id: u32,
    ticket_count: u32,
) -> u64 {
    let hash = solana_program::hash::hashv(&[
        seed,
        &tier_idx.to_le_bytes(),
        &winner_slot.to_le_bytes(),
        &cycle_id.to_le_bytes(),
    ])
    .to_bytes();

    let mut buf = [0u8; 8];
    buf.copy_from_slice(&hash[0..8]);
    u64::from_le_bytes(buf) % (ticket_count as u64)
}

/// Byte size of the registry's administrative metadata header (includes Anchor discriminator).
pub const USER_ENTRY_REGISTRY_HEADER_SIZE: usize =
    8 + std::mem::size_of::<crate::state::TicketRegistry>();
/// Byte size of a single user entry inside the registry.
pub const USER_ENTRY_SIZE: usize = std::mem::size_of::<crate::state::UserEntry>();

/// Helper to calculate and validate the byte start offset for a user entry.
/// Handles checked multiplication, addition, and bounds validation to prevent overflow.
#[inline]
fn get_user_entry_start_offset(data_len: usize, idx: usize) -> Option<usize> {
    idx.checked_mul(USER_ENTRY_SIZE)
        .and_then(|val| val.checked_add(USER_ENTRY_REGISTRY_HEADER_SIZE))
        .filter(|&s| {
            s.checked_add(USER_ENTRY_SIZE)
                .map_or(false, |end| end <= data_len)
        })
}

/// Read the user entry at `idx` from raw account data.
///
/// # Parameters
/// * `data` - Raw bytes slice of the TicketRegistry account data.
/// * `idx` - The zero-based user entry index to fetch.
///
/// # Returns
/// * `UserEntry` - Deserialized user entry struct.
pub fn registry_get_entry(data: &[u8], idx: usize) -> crate::state::UserEntry {
    let start = get_user_entry_start_offset(data.len(), idx)
        .expect("Out of bounds read in registry_get_entry");
    unsafe {
        let ptr = data.as_ptr().add(start) as *const crate::state::UserEntry;
        std::ptr::read_unaligned(ptr)
    }
}

/// Write `entry` into the user entry slot at `idx` in raw account data.
///
/// # Parameters
/// * `data` - Mutable raw bytes slice of the TicketRegistry account data.
/// * `idx` - The zero-based user entry index to write.
/// * `entry` - Reference to the UserEntry struct to be written.
pub fn registry_set_entry(data: &mut [u8], idx: usize, entry: &crate::state::UserEntry) {
    let start = get_user_entry_start_offset(data.len(), idx)
        .expect("Out of bounds write in registry_set_entry");
    unsafe {
        let ptr = data.as_mut_ptr().add(start) as *mut crate::state::UserEntry;
        std::ptr::write_unaligned(ptr, *entry);
    }
}

/// Derive the maximum user entry capacity from the raw account data length.
///
/// # Parameters
/// * `data_len` - Total length of the TicketRegistry account data in bytes.
///
/// # Returns
/// * `u32` - The maximum capacity of user entries that can fit in the account.
pub fn registry_capacity_from_len(data_len: usize) -> u32 {
    ((data_len.saturating_sub(USER_ENTRY_REGISTRY_HEADER_SIZE)) / USER_ENTRY_SIZE) as u32
}

// ─── Unit Tests ──────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    // ── Helpers ──────────────────────────────────────────────────────────────

    /// Construct a deterministic non-default Pubkey from a seed byte.
    fn pk(seed: u8) -> Pubkey {
        Pubkey::new_from_array([seed; 32])
    }

    // ── calculate_percentage_fee ─────────────────────────────────────────────

    #[test]
    fn fee_zero_amount() {
        assert_eq!(calculate_percentage_fee(0, 500), 0);
    }

    #[test]
    fn fee_zero_bps() {
        assert_eq!(calculate_percentage_fee(1_000_000, 0), 0);
    }

    #[test]
    fn fee_full_100_percent() {
        // 10 000 bps == 100 %
        assert_eq!(calculate_percentage_fee(500, 10_000), 500);
    }

    #[test]
    fn fee_50_percent() {
        assert_eq!(calculate_percentage_fee(1_000, 5_000), 500);
    }

    #[test]
    fn fee_1_bps_rounds_down() {
        // 1 bps of 9_999 → 9_999 / 10_000 = 0 (integer truncation)
        assert_eq!(calculate_percentage_fee(9_999, 1), 0);
        // 1 bps of 10_000 → 1
        assert_eq!(calculate_percentage_fee(10_000, 1), 1);
    }

    #[test]
    fn fee_typical_protocol_fee() {
        // 250 bps (2.5%) of 1_000_000 lamports → 25_000
        assert_eq!(calculate_percentage_fee(1_000_000, 250), 25_000);
    }

    #[test]
    fn fee_large_amount() {
        // ensure no overflow for a large but realistic bond amount
        let amount: u64 = 1_000_000_000_000; // 1 trillion lamports
        let fee = calculate_percentage_fee(amount, 100); // 1 %
        assert_eq!(fee, 10_000_000_000);
    }

    #[test]
    fn fee_max_u64_with_1_bps() {
        // (u64::MAX as u128) * 1 / 10_000 must fit back in u64
        let amount = u64::MAX / 10_000; // keeps result within u64
        let fee = calculate_percentage_fee(amount, 1);
        assert_eq!(fee, amount / 10_000);
    }

    // ── derive_random_index ──────────────────────────────────────────────────

    const SEED_A: [u8; 32] = [1u8; 32];
    const SEED_B: [u8; 32] = [2u8; 32];

    #[test]
    fn random_index_in_range() {
        let ticket_count = 100u32;
        let idx = derive_random_index(&SEED_A, 0, 0, 0, ticket_count);
        assert!(idx < ticket_count as u64);
    }

    #[test]
    fn random_index_deterministic() {
        let a = derive_random_index(&SEED_A, 1, 2, 3, 50);
        let b = derive_random_index(&SEED_A, 1, 2, 3, 50);
        assert_eq!(a, b);
    }

    #[test]
    fn random_index_single_ticket() {
        // With ticket_count == 1 the only valid index is 0
        for tier in 0..5 {
            assert_eq!(derive_random_index(&SEED_A, tier, 10, 99, 1), 0);
        }
    }

    #[test]
    fn random_index_different_seeds_differ() {
        // Very unlikely (but not guaranteed) to collide over this many inputs
        let count = 1000u32;
        let a = derive_random_index(&SEED_A, 0, 0, 0, count);
        let b = derive_random_index(&SEED_B, 0, 0, 0, count);
        // Seeds differ → result should differ (statistically near-certain)
        assert_ne!(a, b);
    }

    #[test]
    fn random_index_different_tiers_differ() {
        let count = 10_000u32;
        let a = derive_random_index(&SEED_A, 0, 0, 0, count);
        let b = derive_random_index(&SEED_A, 1, 0, 0, count);
        assert_ne!(a, b);
    }

    #[test]
    fn random_index_different_winner_slots_differ() {
        let count = 10_000u32;
        let a = derive_random_index(&SEED_A, 0, 0, 0, count);
        let b = derive_random_index(&SEED_A, 0, 1, 0, count);
        assert_ne!(a, b);
    }

    #[test]
    fn random_index_different_cycles_differ() {
        let count = 10_000u32;
        let a = derive_random_index(&SEED_A, 0, 0, 1, count);
        let b = derive_random_index(&SEED_A, 0, 0, 2, count);
        assert_ne!(a, b);
    }

    // ── UserEntry Redesign Tests ─────────────────────────────────────────────

    fn make_entry_data(capacity: usize) -> Vec<u8> {
        vec![0u8; USER_ENTRY_REGISTRY_HEADER_SIZE + capacity * USER_ENTRY_SIZE]
    }

    #[test]
    fn test_user_entry_size_and_alignment() {
        use crate::state::UserEntry;
        assert_eq!(std::mem::size_of::<UserEntry>(), 64);

        // Check field offsets manually using raw pointers
        let entry = UserEntry::default();
        let base_ptr = &entry as *const UserEntry as usize;
        let owner_ptr = &entry.owner as *const Pubkey as usize;
        let active_ptr = &entry.active as *const u32 as usize;
        let pending_ptr = &entry.pending as *const u32 as usize;
        let merged_ptr = &entry.merged_through_cycle as *const u32 as usize;
        let cumulative_ptr = &entry.cumulative_active as *const u32 as usize;
        let version_ptr = &entry.version as *const u8 as usize;

        assert_eq!(owner_ptr - base_ptr, 0);
        assert_eq!(active_ptr - base_ptr, 32);
        assert_eq!(pending_ptr - base_ptr, 36);
        assert_eq!(merged_ptr - base_ptr, 40);
        assert_eq!(cumulative_ptr - base_ptr, 44);
        assert_eq!(version_ptr - base_ptr, 48);
    }

    #[test]
    fn test_struct_sizes_are_locked() {
        assert_eq!(std::mem::size_of::<crate::state::TicketRegistry>(), 96);
        assert_eq!(std::mem::size_of::<crate::state::UserEntry>(), 64);
        assert_eq!(std::mem::size_of::<crate::state::PrizeTier>(), 8);
        assert_eq!(std::mem::size_of::<crate::state::PrizePool>(), 392);
        assert_eq!(std::mem::size_of::<crate::state::Winner>(), 32);
        assert_eq!(std::mem::size_of::<crate::state::PayoutRegistry>(), 1688);
        assert_eq!(
            crate::state::GlobalConfig::INIT_SPACE,
            32 + 32 + 4 + 1 + 64
        );
        assert_eq!(
            crate::state::UserWinnings::INIT_SPACE,
            8 + 8 + 8 + 4 + 4 + 32 + 1 + 1 + 64
        );
        assert_eq!(
            crate::state::DrawCycle::INIT_SPACE,
            8 + 8 + 8 + 32 + 4 + 4 + 4 + crate::state::DrawStatus::INIT_SPACE + 1 + 32 + 64
        );
        assert_eq!(
            crate::state::PendingRedemption::INIT_SPACE,
            16 + 8 + 8 + 8 + 8 + 32 + 4 + 1 + 1 + 64
        );
    }

    #[test]
    fn test_zero_copy_8_byte_alignment() {
        assert_eq!(USER_ENTRY_REGISTRY_HEADER_SIZE % 8, 0);
        assert_eq!(USER_ENTRY_SIZE % 8, 0);
        assert_eq!(std::mem::size_of::<crate::state::PrizePool>() % 8, 0);
        assert_eq!(std::mem::size_of::<crate::state::PrizeTier>() % 8, 0);
        assert_eq!(std::mem::size_of::<crate::state::Winner>() % 8, 0);
        assert_eq!(std::mem::size_of::<crate::state::PayoutRegistry>() % 8, 0);
    }

    #[test]
    fn test_pool_status_try_from() {
        use crate::state::PoolStatus;
        assert_eq!(PoolStatus::try_from(0).unwrap(), PoolStatus::Active);
        assert_eq!(PoolStatus::try_from(1).unwrap(), PoolStatus::Paused);
        assert_eq!(PoolStatus::try_from(2).unwrap(), PoolStatus::Closed);
        assert!(PoolStatus::try_from(3).is_err());
        assert!(PoolStatus::try_from(255).is_err());
    }

    #[test]
    fn test_user_entry_capacity_from_len() {
        assert_eq!(registry_capacity_from_len(0), 0);
        assert_eq!(
            registry_capacity_from_len(USER_ENTRY_REGISTRY_HEADER_SIZE - 1),
            0
        );
        assert_eq!(
            registry_capacity_from_len(USER_ENTRY_REGISTRY_HEADER_SIZE),
            0
        );
        assert_eq!(
            registry_capacity_from_len(USER_ENTRY_REGISTRY_HEADER_SIZE + USER_ENTRY_SIZE - 1),
            0
        );
        assert_eq!(
            registry_capacity_from_len(USER_ENTRY_REGISTRY_HEADER_SIZE + USER_ENTRY_SIZE),
            1
        );
        assert_eq!(
            registry_capacity_from_len(USER_ENTRY_REGISTRY_HEADER_SIZE + 10 * USER_ENTRY_SIZE),
            10
        );
    }

    #[test]
    fn test_user_entry_get_set_roundtrip() {
        let mut data = make_entry_data(3);
        let entry1 = crate::state::UserEntry {
            owner: pk(1),
            active: 10,
            pending: 5,
            merged_through_cycle: 2,
            cumulative_active: 15,
            version: 1,
            _reserved: [0; 15],
        };
        let entry2 = crate::state::UserEntry {
            owner: pk(2),
            active: 100,
            pending: 50,
            merged_through_cycle: 4,
            cumulative_active: 150,
            version: 1,
            _reserved: [0; 15],
        };

        registry_set_entry(&mut data, 0, &entry1);
        registry_set_entry(&mut data, 2, &entry2);

        let read1 = registry_get_entry(&data, 0);
        let read2 = registry_get_entry(&data, 2);

        assert_eq!(read1.owner, entry1.owner);
        assert_eq!(read1.active, entry1.active);
        assert_eq!(read1.pending, entry1.pending);
        assert_eq!(read1.merged_through_cycle, entry1.merged_through_cycle);
        assert_eq!(read1.cumulative_active, entry1.cumulative_active);

        assert_eq!(read2.owner, entry2.owner);
        assert_eq!(read2.active, entry2.active);
        assert_eq!(read2.pending, entry2.pending);
        assert_eq!(read2.merged_through_cycle, entry2.merged_through_cycle);
        assert_eq!(read2.cumulative_active, entry2.cumulative_active);
    }

    #[test]
    #[should_panic(expected = "Out of bounds read in registry_get_entry")]
    fn test_user_entry_get_out_of_bounds_panics() {
        let data = make_entry_data(2);
        // capacity is 2 (valid indices 0 and 1)
        let _ = registry_get_entry(&data, 2);
    }

    #[test]
    #[should_panic(expected = "Out of bounds write in registry_set_entry")]
    fn test_user_entry_set_out_of_bounds_panics() {
        let mut data = make_entry_data(2);
        let entry = crate::state::UserEntry::default();
        registry_set_entry(&mut data, 2, &entry);
    }

    #[test]
    fn test_lazy_merge_transitions() {
        let mut entry = crate::state::UserEntry {
            owner: pk(1),
            active: 10,
            pending: 5,
            merged_through_cycle: 2,
            cumulative_active: 0,
            version: 1,
            _reserved: [0; 15],
        };

        // Case 1: merged_through_cycle < current_cycle_id -> should merge
        assert!(entry.lazy_merge(3).is_ok());
        assert_eq!(entry.active, 15);
        assert_eq!(entry.pending, 0);
        assert_eq!(entry.merged_through_cycle, 3);

        // Case 2: merged_through_cycle == current_cycle_id -> should not merge again
        entry.pending = 8; // set some pending again in same cycle
        assert!(entry.lazy_merge(3).is_ok());
        assert_eq!(entry.active, 15);
        assert_eq!(entry.pending, 8);
        assert_eq!(entry.merged_through_cycle, 3);

        // Case 3: merged_through_cycle > current_cycle_id -> should not merge (already ahead)
        assert!(entry.lazy_merge(2).is_ok());
        assert_eq!(entry.active, 15);
        assert_eq!(entry.pending, 8);
        assert_eq!(entry.merged_through_cycle, 3);

        // Case 4: overflow check -> should fail
        entry.pending = u32::MAX;
        assert!(entry.lazy_merge(4).is_err());
    }
}
