[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
anchor = "4ZJJemMiVfNzwwoz8BedkWZ8ZKCkx1ya6iA59JS6baGG"
mock_huma = "ECMEF6mYCd3YqWk2jwZraPqJTz1bWDwLKrD2Ldgq3wKz"
mock_kamino = "GVkUHNohGv2AqewpZnciXhjwt3diSsLuDAKp1Q1bH1GA"
mock_switchboard = "Aio4gaXjXzJNVLtzwtNVmSqGKpANtXhybbkhtAC94ji2"

[programs.devnet]
anchor = "4ZJJemMiVfNzwwoz8BedkWZ8ZKCkx1ya6iA59JS6baGG"
mock_huma = "ECMEF6mYCd3YqWk2jwZraPqJTz1bWDwLKrD2Ldgq3wKz"
mock_kamino = "GVkUHNohGv2AqewpZnciXhjwt3diSsLuDAKp1Q1bH1GA"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
