[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
anchor = "3GTfYY4nefPvDpeUuyVjqCVUCtvhBMga82RjLVn6MTos"
mock_huma = "4VSPD3TcxWc98Ed6e6vAYshrqsrpHHqvXCB4W73JQtXg"
mock_kamino = "GVkUHNohGv2AqewpZnciXhjwt3diSsLuDAKp1Q1bH1GA"

[programs.devnet]
anchor = "3GTfYY4nefPvDpeUuyVjqCVUCtvhBMga82RjLVn6MTos"
mock_huma = "4VSPD3TcxWc98Ed6e6vAYshrqsrpHHqvXCB4W73JQtXg"
mock_kamino = "GVkUHNohGv2AqewpZnciXhjwt3diSsLuDAKp1Q1bH1GA"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
