[workspace]
members = [
    "programs/*"
]
resolver = "2"

[workspace.lints.rust]
unexpected_cfgs = { level = "allow", check-cfg = ['cfg(target_os, values("solana"))'] }
dead_code = "allow"
unused_variables = "allow"
unused_mut = "allow"
unused_must_use = "allow"
unused_imports = "allow"

[workspace.lints.clippy]
result_large_err = "allow"
too_many_arguments = "allow"

[profile.release]
overflow-checks = true
lto = "fat"
codegen-units = 1
[profile.release.build-override]
opt-level = 3
incremental = false
codegen-units = 1

[profile.dev]
opt-level = 1

[profile.test]
opt-level = 1

[patch.crates-io]
solana-program-ed25519-dalek-bump = { path = "patches/solana-program-ed25519-dalek-bump" }


