import { describe, it, before, after } from "node:test";
import assert from "node:assert/strict";
import * as fs from "node:fs";
import * as path from "node:path";
import * as os from "node:os";
import { parseEnvLine, readEnvFile, upsertEnvFile } from "./env-utils";

describe("Environment File Utilities (env-utils)", () => {
  let testDir: string;

  before(() => {
    testDir = fs.mkdtempSync(path.join(os.tmpdir(), "pb-env-test-"));
  });

  after(() => {
    if (testDir && fs.existsSync(testDir)) {
      fs.rmSync(testDir, { recursive: true, force: true });
    }
  });

  it("should parse active variables, comments, whitespace, and export prefixes", () => {
    const active = parseEnvLine("DATABASE_URL=postgres://localhost:5432/db");
    assert.strictEqual(
      active.isCommentOrBlank,
      false,
      "Active line should not be comment or blank"
    );
    assert.strictEqual(
      active.key,
      "DATABASE_URL",
      "Key should be DATABASE_URL"
    );
    assert.strictEqual(
      active.value,
      "postgres://localhost:5432/db",
      "Value should match raw postgres URL"
    );

    const withExport = parseEnvLine(
      "export NEXT_PUBLIC_RPC=http://127.0.0.1:8899"
    );
    assert.strictEqual(
      withExport.isCommentOrBlank,
      false,
      "Export prefix line should not be comment"
    );
    assert.strictEqual(
      withExport.key,
      "NEXT_PUBLIC_RPC",
      "Key should strip export keyword"
    );
    assert.strictEqual(
      withExport.value,
      "http://127.0.0.1:8899",
      "Export value should match URL"
    );

    const doubleQuoted = parseEnvLine('SECRET_KEY="abc 123 # not comment"');
    assert.strictEqual(doubleQuoted.key, "SECRET_KEY", "Key match");
    assert.strictEqual(
      doubleQuoted.value,
      "abc 123 # not comment",
      "Quoted value with hash should be preserved"
    );

    const singleQuoted = parseEnvLine("SINGLE_KEY='xyz'");
    assert.strictEqual(singleQuoted.key, "SINGLE_KEY", "Key match");
    assert.strictEqual(singleQuoted.value, "xyz", "Single quoted value match");

    const commentLine = parseEnvLine("# DATABASE_URL=old_url");
    assert.strictEqual(
      commentLine.isCommentOrBlank,
      true,
      "Commented out key should be comment"
    );
    assert.strictEqual(
      commentLine.key,
      undefined,
      "Comment should have undefined key"
    );

    const emptyLine = parseEnvLine("   ");
    assert.strictEqual(
      emptyLine.isCommentOrBlank,
      true,
      "Whitespace should be comment or blank"
    );
  });

  it("should read and parse .env dictionary cleanly", () => {
    const samplePath = path.resolve(testDir, "test.env");
    fs.writeFileSync(
      samplePath,
      `# Top comment
DATABASE_URL=postgres://user:pass@host:5432/db
# HELIUS_API_KEY=unused
NEXT_PUBLIC_ENVIRONMENT=localnet
export PUSHER_KEY="key123"
`,
      "utf-8"
    );

    const parsed = readEnvFile(samplePath);
    assert.strictEqual(
      parsed.DATABASE_URL,
      "postgres://user:pass@host:5432/db",
      "DATABASE_URL should match parsed connection string"
    );
    assert.strictEqual(
      parsed.NEXT_PUBLIC_ENVIRONMENT,
      "localnet",
      "NEXT_PUBLIC_ENVIRONMENT should match"
    );
    assert.strictEqual(
      parsed.PUSHER_KEY,
      "key123",
      "PUSHER_KEY should match without quotes"
    );
    assert.strictEqual(
      parsed.HELIUS_API_KEY,
      undefined,
      "Comment should not be parsed as key"
    );
  });

  it("should preserve unmanaged variables, comments, and replace existing keys in-place", () => {
    const testFile = path.resolve(testDir, "local.env");
    fs.writeFileSync(
      testFile,
      `# User custom database config
DATABASE_URL=postgresql://localhost:5432/my_app
MY_SECRET=supersecret

# Solana config
NEXT_PUBLIC_ENVIRONMENT=old_env
NEXT_PUBLIC_SOLANA_RPC_URL=http://localhost:8899
`,
      "utf-8"
    );

    upsertEnvFile(
      testFile,
      {
        NEXT_PUBLIC_ENVIRONMENT: "localnet",
        NEXT_PUBLIC_ADMIN_ADDRESS: "AdminPubkey11111111111111111111111111",
      },
      { headerComment: "# Generated by localnet orchestrator" }
    );

    const updatedContent = fs.readFileSync(testFile, "utf-8");
    const parsed = readEnvFile(testFile);

    // Unmanaged keys preserved
    assert.strictEqual(
      parsed.DATABASE_URL,
      "postgresql://localhost:5432/my_app",
      "DATABASE_URL must be preserved"
    );
    assert.strictEqual(
      parsed.MY_SECRET,
      "supersecret",
      "MY_SECRET must be preserved"
    );

    // Managed keys updated & appended
    assert.strictEqual(
      parsed.NEXT_PUBLIC_ENVIRONMENT,
      "localnet",
      "NEXT_PUBLIC_ENVIRONMENT must be updated"
    );
    assert.strictEqual(
      parsed.NEXT_PUBLIC_ADMIN_ADDRESS,
      "AdminPubkey11111111111111111111111111",
      "NEXT_PUBLIC_ADMIN_ADDRESS must be appended"
    );

    // Comments preserved
    assert.ok(
      updatedContent.includes("# User custom database config"),
      "Original user comments must be preserved"
    );
    assert.ok(
      updatedContent.includes("# Solana config"),
      "Original category comments must be preserved"
    );
  });

  it("should create non-existent file cleanly with header comment on upsert", () => {
    const newFile = path.resolve(testDir, "brand_new.env");
    if (fs.existsSync(newFile)) {
      fs.unlinkSync(newFile);
    }

    upsertEnvFile(
      newFile,
      {
        FOO: "bar",
        BAZ: "qux",
      },
      { headerComment: "# Auto-generated config" }
    );

    assert.ok(fs.existsSync(newFile), "Brand new file should be created");
    const content = fs.readFileSync(newFile, "utf-8");
    assert.ok(
      content.startsWith("# Auto-generated config"),
      "Header comment should be positioned at the top"
    );
    const parsed = readEnvFile(newFile);
    assert.strictEqual(parsed.FOO, "bar");
    assert.strictEqual(parsed.BAZ, "qux");
  });

  it("should handle missing trailing newlines and guarantee upsert idempotency", () => {
    const noTrailingNewlineFile = path.resolve(testDir, "no_newline.env");
    fs.writeFileSync(
      noTrailingNewlineFile,
      "DATABASE_URL=postgres://localhost:5432/db",
      "utf-8"
    );

    // First upsert
    upsertEnvFile(
      noTrailingNewlineFile,
      {
        RPC_URL: "http://127.0.0.1:8899",
      },
      { headerComment: "# Header comment" }
    );

    const firstPass = fs.readFileSync(noTrailingNewlineFile, "utf-8");
    assert.ok(
      !firstPass.includes("DATABASE_URL=postgres://localhost:5432/dbRPC_URL"),
      "Must not collide lines when original file lacks trailing newline"
    );

    // Second upsert (idempotency check)
    upsertEnvFile(
      noTrailingNewlineFile,
      {
        RPC_URL: "http://127.0.0.1:8899",
      },
      { headerComment: "# Header comment" }
    );

    const secondPass = fs.readFileSync(noTrailingNewlineFile, "utf-8");
    const headerCount = (secondPass.match(/# Header comment/g) || []).length;
    assert.strictEqual(
      headerCount,
      1,
      `Header comment should appear exactly once, found ${headerCount}`
    );

    const parsed = readEnvFile(noTrailingNewlineFile);
    assert.strictEqual(
      parsed.DATABASE_URL,
      "postgres://localhost:5432/db",
      "DATABASE_URL preserved across multiple upserts"
    );
    assert.strictEqual(
      parsed.RPC_URL,
      "http://127.0.0.1:8899",
      "RPC_URL set correctly across multiple upserts"
    );
  });
});
