import * as fs from "fs";
import * as path from "path";
import { parseEnvLine, readEnvFile, upsertEnvFile } from "./env-utils";

function assert(condition: boolean, message: string) {
  if (!condition) {
    throw new Error(`Assertion failed: ${message}`);
  }
}

function runTests() {
  console.log("Running scripts/env-utils.test.ts unit tests...\n");

  const testDir = path.resolve(__dirname, "test-scratch");
  if (!fs.existsSync(testDir)) {
    fs.mkdirSync(testDir, { recursive: true });
  }

  // Test 1: parseEnvLine correctly parses active variables, comments, and export prefix
  {
    console.log("Test 1: parseEnvLine parsing rules");
    const active = parseEnvLine("DATABASE_URL=postgres://localhost:5432/db");
    assert(!active.isCommentOrBlank, "Should not be comment or blank");
    assert(active.key === "DATABASE_URL", "Key should be DATABASE_URL");
    assert(
      active.value === "postgres://localhost:5432/db",
      "Value should match"
    );

    const withExport = parseEnvLine(
      "export NEXT_PUBLIC_RPC=http://127.0.0.1:8899"
    );
    assert(!withExport.isCommentOrBlank, "Export should not be comment");
    assert(
      withExport.key === "NEXT_PUBLIC_RPC",
      "Key should be NEXT_PUBLIC_RPC"
    );
    assert(
      withExport.value === "http://127.0.0.1:8899",
      "Export value should match"
    );

    const doubleQuoted = parseEnvLine('SECRET_KEY="abc 123 # not comment"');
    assert(doubleQuoted.key === "SECRET_KEY", "Key match");
    assert(
      doubleQuoted.value === "abc 123 # not comment",
      "Quoted value match"
    );

    const singleQuoted = parseEnvLine("SINGLE_KEY='xyz'");
    assert(singleQuoted.key === "SINGLE_KEY", "Key match");
    assert(singleQuoted.value === "xyz", "Single quoted value match");

    const commentLine = parseEnvLine("# DATABASE_URL=old_url");
    assert(commentLine.isCommentOrBlank, "Commented out key should be comment");
    assert(commentLine.key === undefined, "Comment should have undefined key");

    const emptyLine = parseEnvLine("   ");
    assert(emptyLine.isCommentOrBlank, "Whitespace should be comment or blank");

    console.log("✓ Passed Test 1\n");
  }

  // Test 2: readEnvFile parses dictionary properly
  {
    console.log("Test 2: readEnvFile parsing dictionary");
    const samplePath = path.resolve(testDir, "test.env");
    fs.writeFileSync(
      samplePath,
      `# Top comment
DATABASE_URL=postgres://user:pass@host:5432/db
# HELIUS_API_KEY=unused
NEXT_PUBLIC_ENVIRONMENT=localnet
export PUSHER_KEY="key123"
`,
      "utf-8"
    );

    const parsed = readEnvFile(samplePath);
    assert(
      parsed.DATABASE_URL === "postgres://user:pass@host:5432/db",
      "DATABASE_URL mismatch"
    );
    assert(
      parsed.NEXT_PUBLIC_ENVIRONMENT === "localnet",
      "ENVIRONMENT mismatch"
    );
    assert(parsed.PUSHER_KEY === "key123", "PUSHER_KEY mismatch");
    assert(
      parsed.HELIUS_API_KEY === undefined,
      "Comment should not be parsed as key"
    );

    console.log("✓ Passed Test 2\n");
  }

  // Test 3: upsertEnvFile preserves unmanaged variables, comments, and replaces existing keys in-place
  {
    console.log("Test 3: upsertEnvFile preserves unmanaged keys and comments");
    const testFile = path.resolve(testDir, "local.env");
    fs.writeFileSync(
      testFile,
      `# User custom database config
DATABASE_URL=postgresql://localhost:5432/my_app
MY_SECRET=supersecret

# Solana config
NEXT_PUBLIC_ENVIRONMENT=old_env
NEXT_PUBLIC_SOLANA_RPC_URL=http://localhost:8899
`,
      "utf-8"
    );

    upsertEnvFile(
      testFile,
      {
        NEXT_PUBLIC_ENVIRONMENT: "localnet",
        NEXT_PUBLIC_ADMIN_ADDRESS: "AdminPubkey11111111111111111111111111",
      },
      { headerComment: "# Generated by localnet orchestrator" }
    );

    const updatedContent = fs.readFileSync(testFile, "utf-8");
    const parsed = readEnvFile(testFile);

    // Unmanaged keys preserved
    assert(
      parsed.DATABASE_URL === "postgresql://localhost:5432/my_app",
      "DATABASE_URL must be preserved"
    );
    assert(parsed.MY_SECRET === "supersecret", "MY_SECRET must be preserved");

    // Managed keys updated & appended
    assert(
      parsed.NEXT_PUBLIC_ENVIRONMENT === "localnet",
      "NEXT_PUBLIC_ENVIRONMENT must be updated"
    );
    assert(
      parsed.NEXT_PUBLIC_ADMIN_ADDRESS ===
        "AdminPubkey11111111111111111111111111",
      "NEXT_PUBLIC_ADMIN_ADDRESS must be appended"
    );

    // Comments preserved
    assert(
      updatedContent.includes("# User custom database config"),
      "Original comments must be preserved"
    );
    assert(
      updatedContent.includes("# Solana config"),
      "Original comments must be preserved"
    );

    console.log("✓ Passed Test 3\n");
  }

  // Test 4: upsertEnvFile on missing file creates it cleanly with header
  {
    console.log("Test 4: upsertEnvFile on non-existent file");
    const newFile = path.resolve(testDir, "brand_new.env");
    if (fs.existsSync(newFile)) {
      fs.unlinkSync(newFile);
    }

    upsertEnvFile(
      newFile,
      {
        FOO: "bar",
        BAZ: "qux",
      },
      { headerComment: "# Auto-generated config" }
    );

    assert(fs.existsSync(newFile), "File should be created");
    const content = fs.readFileSync(newFile, "utf-8");
    assert(
      content.startsWith("# Auto-generated config"),
      "Header comment should be at top"
    );
    const parsed = readEnvFile(newFile);
    assert(parsed.FOO === "bar" && parsed.BAZ === "qux", "Keys should match");

    console.log("✓ Passed Test 4\n");
  }

  // Test 5: Idempotency & file without trailing newline
  {
    console.log("Test 5: Idempotency & missing trailing newline handling");
    const noTrailingNewlineFile = path.resolve(testDir, "no_newline.env");
    fs.writeFileSync(
      noTrailingNewlineFile,
      "DATABASE_URL=postgres://localhost:5432/db",
      "utf-8"
    );

    // First upsert
    upsertEnvFile(
      noTrailingNewlineFile,
      {
        RPC_URL: "http://127.0.0.1:8899",
      },
      { headerComment: "# Header comment" }
    );

    const firstPass = fs.readFileSync(noTrailingNewlineFile, "utf-8");
    assert(
      !firstPass.includes("DATABASE_URL=postgres://localhost:5432/dbRPC_URL"),
      "Must not collide lines when missing trailing newline"
    );

    // Second upsert (idempotency check)
    upsertEnvFile(
      noTrailingNewlineFile,
      {
        RPC_URL: "http://127.0.0.1:8899",
      },
      { headerComment: "# Header comment" }
    );

    const secondPass = fs.readFileSync(noTrailingNewlineFile, "utf-8");
    // Count occurrences of header comment
    const headerCount = (secondPass.match(/# Header comment/g) || []).length;
    assert(
      headerCount === 1,
      `Header comment should appear exactly once, found ${headerCount}`
    );

    const parsed = readEnvFile(noTrailingNewlineFile);
    assert(
      parsed.DATABASE_URL === "postgres://localhost:5432/db",
      "DATABASE_URL preserved"
    );
    assert(parsed.RPC_URL === "http://127.0.0.1:8899", "RPC_URL set");

    console.log("✓ Passed Test 5\n");
  }

  // Cleanup test scratch
  fs.rmSync(testDir, { recursive: true, force: true });

  console.log("All env-utils unit tests completed successfully!");
}

runTests();
